### ISSUE TITLE
#你必须创建系统所需要的所有技能及物品模板，详情请查看bossHunter.w3x，建议使用bossHunter.w3x进行二次开发

### ISSUE THREAD

**Issue by jjjjax** [hunzsig-warcraft3/h-lua#4]
这个bossHunter能提供一下下载嘛？

**Comment by jjjjax** [comment]
再悄悄咪咪地问一下， 作者有没有交流群之类的？

**Comment by hunzsig** [comment]
> 再悄悄咪咪地问一下， 作者有没有交流群之类的？
地图是旧版的，现在已经不适合参考了。暂时没有完整的演示，还处于修bug完善期。
QQ群 325338043
